### PR TITLE
add ability to snap to n items

### PR DESCRIPTION
**Pull request by ahamula**
Hi @chrisbanes .
I need a feature to snap n items, not only one.
I'd appreciate if you'll look on my changes to support this case or at least to say if snapper is going to support this case.

### CODE REVIEW

**Comment by chrisbanes** [comment]
This feature is already covered by the `maximumFlingDistance` parameter. You can provide the width of 2 items in pixels, using the given `SnapperLayoutInfo`.

**Comment by ahamula** [comment]
It's a bit different.
For example it should scroll per 3 items.
After you lift the finger, it should scroll to the index multiple to 3.

**Comment by chrisbanes** [comment]
Ahhhh, so it's snapping to groups of items? Let me have a think on what the API could look like for this.

**Comment by chrisbanes** [comment]
Had a think through this today and I think the API for this should be something like:

```
rememberSnapperFlingBehavior(
    lazyListState = ...,
    snapIndex = { calculatedTargetIndex ->
       // round down/up to nearest group
    }
)
```

WDYT?

**Comment by ahamula** [comment]
Nice, it works perfectly as far as I tested.

**Pull request closed without merging**
